# org: sturoscyglobus
# app: esgf2-index-serverless
frameworkVersion: "3"
service: esgf2-index-serverless

provider:
  name: aws
  runtime: python3.11

functions:
  search:
    handler: app.main.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-python-requirements
