org: argonne
app: esgf2-index-serverless
service: esgf2-index-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11

functions:
  search:
    handler: app.main.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-python-requirements
