version: 0.2

phases:
  pre_build:
    commands:
      - echo Zipping project and uploading to S3
      - zip -r $PROJECT_FOLDER/esgf2-index.zip $PROJECT_FOLDER
      - aws s3api put-object --bucket $S3_CODE_BUCKET text-content --key esgf2-index.zip --body $PROJECT_FOLDER/esgf2-index.zip
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --profile default --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
